include:
  - project: repos/m3api/tmp-m3api
    file: /.gitlab-ci-template.yml

stages:
  - test
  - release

test-job:
  extends: .test-job

test-package-lock-job:
  extends: .test-package-lock-job

release-job:
  extends: .release-job

publish-job:
  extends: .publish-job

doc-job:
  extends: .doc-job
